CREATE INDEX idx_dfe_ev_cce_lob_json_id ON msaf_dfe.dfe_evento_carta_correcao_nfe(dfe_lob_json_id);
CREATE INDEX idx_dfe_ev_canc_lob_ret_canc ON msaf_dfe.dfe_evento_canc_nfe(dfe_lob_ret_canc_sefaz_id);
